-- Create tables for AI-generated community posts and schedule management
-- Enables admin-controlled scheduling of AI content generation

-- Extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1) Schedules table: defines recurring jobs or one-off configs
CREATE TABLE IF NOT EXISTS public.ai_post_schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  cron text NOT NULL,            -- cron expression (e.g. "0 9 * * 1")
  prompt_template text NOT NULL, -- prompt with placeholders like ${genre}
  categories text[] DEFAULT '{}',
  language_style text,
  min_words int,
  max_words int,
  enabled boolean DEFAULT true,
  auto_publish boolean DEFAULT false,
  last_run_at timestamptz
);

-- 2) Drafts / posts table generated by AI
CREATE TABLE IF NOT EXISTS public.ai_post_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id uuid REFERENCES public.ai_post_schedules(id) ON DELETE SET NULL,
  title text NOT NULL,
  content text NOT NULL,
  tags text[] DEFAULT '{}',
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')),
  is_ai_generated boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  published_at timestamptz
);

-- 3) Simple index to query drafts by status
CREATE INDEX IF NOT EXISTS idx_ai_post_drafts_status ON public.ai_post_drafts(status); 