-- scraped_posts 테이블: 외부 커뮤니티/사이트에서 가져온 전시·미술 관련 글 저장
CREATE TABLE IF NOT EXISTS public.scraped_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,                 -- 'visitseoul' | 'cultureSeoul' | ...
  post_url TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  thumb_url TEXT,                       -- Supabase Storage 업로드 후 공개 URL
  summary TEXT,
  score INTEGER DEFAULT 0,
  scraped_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  used BOOLEAN DEFAULT FALSE
);

-- 간단 RLS: 읽기는 공개, 쓰기는 서비스 롤
ALTER TABLE public.scraped_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "scraped_read" ON public.scraped_posts FOR SELECT USING (true);
CREATE POLICY "scraped_insert" ON public.scraped_posts FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "scraped_update" ON public.scraped_posts FOR UPDATE USING (auth.role() = 'service_role'); 